            - name: OpenAI Chat
  # You may pin to the exact commit or the version.
  # uses: fukumone/openai-chat@767ab6df693837f027900bdec7e54617e2f3bc06
  uses: fukumone/openai-chat@v0.0.2
  with:
    # Your openai api key
    openai-api-key: 
    # The comment that was posted on GitHub
    github-comment: # optional
    # GitHub access token with permissions to access the repository where the comment was posted
    github-token: 
    # The model to use
    model: # optional, default is text-davinci-003
          
